FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /KalininHutor.API

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
RUN dotnet build
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /KalininHutor.API
COPY --from=build-env /KalininHutor.API/out .
ENTRYPOINT ["dotnet", "/KalininHutor.API/KalininHutor.API.dll"]