name: Build and deploy project

on:
  push:
    branches: [ "dev", "feature/**" ]

jobs:
  client-build:
    env: 
      CI: false
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./kalinin-hutor
    steps:    
    - uses: actions/checkout@v3
     
    - name: Setup Node
      uses: actions/setup-node@v3
  
    - name: Install dependencies
      run: npm ci
  
    - name: Build app
      run: npm run build:prod

  api-build:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./KalininHutor.API
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish KalininHutor.API.csproj -c Release -o api