name: Build project

on:
  push:
    branches: [ "dev", "feature/*", "master" ]

jobs:
  client-build:
    runs-on: windows-2019
    steps:
    - name: Setup Node
      run: npm install
      working-directory: .\kalinin-hutor
      
    - name: Build app
      run: |
        npm ci
        npm run build
      working-directory: .\kalinin-hutor

  api-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
